# Stages the webcore directory + JUCE's WebView frontend library into one zip.
# Run via: cmake -DSRC=... -DJUCEJS=... -DSTAGE=... -DOUT=... -P PackWebcore.cmake
#
# The JUCE js module is injected at /juce/index.js so the web app can simply
#   import { getNativeFunction } from "/juce/index.js";
# without pulling the juce-framework-frontend npm package.

if(NOT EXISTS "${SRC}")
    message(FATAL_ERROR "PackWebcore: source dir does not exist: ${SRC}")
endif()

file(REMOVE_RECURSE "${STAGE}")
file(MAKE_DIRECTORY "${STAGE}")

file(COPY "${SRC}/" DESTINATION "${STAGE}"
     PATTERN ".DS_Store" EXCLUDE
     PATTERN ".git*" EXCLUDE
     PATTERN "node_modules" EXCLUDE)

file(MAKE_DIRECTORY "${STAGE}/juce")
file(COPY "${JUCEJS}" DESTINATION "${STAGE}/juce")

# ---------------------------------------------------------------------------
# juce/juce-global.js - the same library as a CLASSIC script.
#
# WKWebView refuses ES module scripts served over JUCE's juce:// scheme
# ("Importing a module script failed"), even though fetch(), classic scripts and
# Web Workers all work fine over it. So a page loaded in the plugin cannot use
# <script type="module"> at all on macOS.
#
# This rewrites JUCE's ES module into a classic script exposing window.Juce, so
# the web app can just do:
#     <script src="./juce/juce-global.js"></script>
#     const f = Juce.getNativeFunction("getShellInfo");
# The transform is mechanical: inline the one import, turn the export list into
# an object literal, and wrap the lot so nothing else leaks into global scope.
# ---------------------------------------------------------------------------
get_filename_component(JUCEJS_DIR "${JUCEJS}" DIRECTORY)
file(READ "${JUCEJS}" juce_js)
file(READ "${JUCEJS_DIR}/check_native_interop.js" interop_js)

string(REPLACE "import \"./check_native_interop.js\";" "${interop_js}" juce_js "${juce_js}")

# `export { a, b, c, };` -> `window.Juce = { a, b, c, };` (shorthand properties)
string(REPLACE "export {" "window.Juce = {" juce_js "${juce_js}")

if(juce_js MATCHES "(^|\n)[ \t]*(import|export)[ \t]")
    message(FATAL_ERROR "PackWebcore: module syntax survived the juce-global.js transform. "
                        "JUCE's index.js layout changed - update cmake/PackWebcore.cmake.")
endif()

file(WRITE "${STAGE}/juce/juce-global.js"
     "// Generated by cmake/PackWebcore.cmake from JUCE's juce_gui_extra frontend library.\n"
     "// Classic script (NOT a module): WKWebView will not load modules over juce://.\n"
     "(function () {\n${juce_js}\n})();\n")

if(NOT EXISTS "${STAGE}/index.html")
    message(FATAL_ERROR "PackWebcore: ${SRC} has no index.html - that is the webcore entry point.")
endif()

# Write to a temp name then rename, so a half-written zip is never picked up.
file(REMOVE "${OUT}" "${OUT}.tmp")
file(GLOB stage_entries RELATIVE "${STAGE}" "${STAGE}/*")
execute_process(
    COMMAND ${CMAKE_COMMAND} -E tar cf "${OUT}.tmp" --format=zip -- ${stage_entries}
    WORKING_DIRECTORY "${STAGE}"
    RESULT_VARIABLE zip_result
    OUTPUT_VARIABLE zip_out
    ERROR_VARIABLE zip_err)
if(NOT zip_result EQUAL 0)
    message(FATAL_ERROR "PackWebcore: zip failed: ${zip_err}${zip_out}")
endif()
file(RENAME "${OUT}.tmp" "${OUT}")
message(STATUS "PackWebcore: ${SRC} -> ${OUT}")
