#include <JuceHeader.h>
#include <BinaryData.h>

#include "basicpitch/BasicPitchFrontend.h"
#include "basicpitch/BasicPitchNotes.h"
#include "onnx/ModelLocator.h"
#include "onnx/OrtSession.h"

/**
    The built-in engine, from the model bytes to the note list.

    WHAT THESE TESTS ARE FOR. Basic Pitch's failure mode is not a crash: a wrong
    hop size, a mis-stitched window or an off-by-one in the unwrap all produce
    perfectly plausible notes at slightly wrong times, and no smoke test catches
    that. So the golden fixtures here are NOT generated by this code. They come
    from spotify/basic-pitch's own note_creation.py, run over posteriorgrams
    produced by onnxruntime's Python bindings, by scratchpad/make_golden.py:

        shell/test/BasicPitchFixture.wav  - a synthetic bass riff, 4.3 s, five
                                            notes, one of them deliberately far
                                            above any bass range
        shell/test/BasicPitchGolden.bin   - the note and onset posteriorgrams
                                            upstream produced from that wav
        shell/test/BasicPitchGolden.json  - the notes upstream's post-processor
                                            found in them, with and without the
                                            bass frequency bound

    So "the C++ agrees with the reference" is a real claim here rather than "the
    C++ agrees with itself". The chain is proved in both directions: the C++
    front end must reproduce upstream's posteriorgrams from the same wav, and the
    C++ post-processor must reproduce upstream's notes from the committed ones.

    A real recording is deliberately not used as a fixture anywhere here: it is
    a CAF stream in a .wav container and every engine gets nothing out of it, so
    a test built on it would pass while proving nothing.
*/
class BasicPitchTests final : public juce::UnitTest
{
public:
    BasicPitchTests() : juce::UnitTest ("BasicPitch", "BasicPitch") {}

    //== fixtures =============================================================

    static juce::File testDir()
    {
       #ifdef RIFFSHEET_TEST_DIR
        return juce::File (RIFFSHEET_TEST_DIR);
       #else
        return {};
       #endif
    }

    struct Golden
    {
        BasicPitchFrontend::Posteriorgram notes, onsets;
        int frames = 0, bins = 0;
    };

    /** Reads the .bin: "RSBP", uint32 version, uint32 frames, uint32 bins, then
        frames*bins float32 of notes followed by the same of onsets. */
    bool loadGoldenBin (Golden& out)
    {
        const auto file = testDir().getChildFile ("BasicPitchGolden.bin");
        juce::MemoryBlock block;

        if (! file.loadFileAsData (block) || block.getSize() < 16)
            return false;

        const auto* bytes = static_cast<const uint8_t*> (block.getData());

        if (std::memcmp (bytes, "RSBP", 4) != 0)
            return false;

        uint32_t header[3] {};
        std::memcpy (header, bytes + 4, sizeof (header));

        out.frames = (int) header[1];
        out.bins = (int) header[2];

        const auto count = (size_t) out.frames * (size_t) out.bins;

        if (block.getSize() != 16 + count * 2 * sizeof (float))
            return false;

        const auto* floats = reinterpret_cast<const float*> (bytes + 16);

        const auto read = [&] (BasicPitchFrontend::Posteriorgram& target, size_t offset)
        {
            target.resize ((size_t) out.frames);

            for (size_t f = 0; f < target.size(); ++f)
                target[f].assign (floats + offset + f * (size_t) out.bins,
                                  floats + offset + (f + 1) * (size_t) out.bins);
        };

        read (out.notes, 0);
        read (out.onsets, count);
        return true;
    }

    juce::var loadGoldenJson()
    {
        return juce::JSON::parse (testDir().getChildFile ("BasicPitchGolden.json"));
    }

    void expectMatchesGolden (const std::vector<BasicPitchNotes::Event>& events,
                              const juce::var& expected,
                              const juce::String& what)
    {
        const auto* list = expected.getArray();

        if (list == nullptr)
        {
            expect (false, what + ": the golden list is missing");
            return;
        }

        expectEquals ((int) events.size(), list->size(), what + ": note count");

        const auto shared = juce::jmin ((int) events.size(), list->size());

        for (int i = 0; i < shared; ++i)
        {
            const auto& got = events[(size_t) i];
            const auto& want = list->getReference (i);

            const auto label = what + " note " + juce::String (i);
            expectEquals (got.startFrame, (int) want["startFrame"], label + " startFrame");
            expectEquals (got.endFrame, (int) want["endFrame"], label + " endFrame");
            expectEquals (got.pitch, (int) want["pitch"], label + " pitch");
            expect (std::abs (got.amplitude - (double) want["amplitude"]) < 1.0e-4,
                    label + " amplitude: got " + juce::String (got.amplitude, 6)
                          + ", golden " + juce::String ((double) want["amplitude"], 6));
        }
    }

    //== the tests ============================================================

    void runTest() override
    {
        beginTest ("the fixtures are where the build says they are");
        {
            expect (testDir().isDirectory(),
                    "RIFFSHEET_TEST_DIR is not a directory: " + testDir().getFullPathName());
            expect (testDir().getChildFile ("BasicPitchFixture.wav").existsAsFile());
            expect (testDir().getChildFile ("BasicPitchGolden.bin").existsAsFile());
            expect (testDir().getChildFile ("BasicPitchGolden.json").existsAsFile());
        }

        beginTest ("the framing constants are upstream's, arithmetically");
        {
            // Every one of these is derived, so a typo in one constant shows up
            // as a wrong number here rather than as plausible notes at the wrong
            // time. The right-hand sides are basic_pitch/constants.py's.
            expectEquals (BasicPitchFrontend::kSampleRate, 22050);
            expectEquals (BasicPitchFrontend::kFftHop, 256);
            expectEquals (BasicPitchFrontend::kAnnotationsFps, 86);
            expectEquals (BasicPitchFrontend::kFramesPerWindow, 172);
            expectEquals (BasicPitchFrontend::kSamplesPerWindow, 43844);
            expectEquals (BasicPitchFrontend::kOverlapSamples, 7680);
            expectEquals (BasicPitchFrontend::kHopSamples, 36164);
            expectEquals (BasicPitchFrontend::kTrimFramesPerSide, 15);
            expectEquals (BasicPitchFrontend::kFramesKeptPerWindow, 142);
            expectEquals (BasicPitchFrontend::kLeadingPadSamples, 3840);
            expectEquals (BasicPitchFrontend::kNoteBins, 88);
            expectEquals (BasicPitchFrontend::kMidiOffset, 21);
        }

        beginTest ("framing a fixed-length input gives the frame count upstream gives");
        {
            // 4.3 s at 22050 Hz is the committed fixture; upstream's Python run
            // produced 3 windows and 369 unwrapped frames, and those two numbers
            // are recorded in the golden JSON so this is a comparison, not a
            // restatement.
            const auto golden = loadGoldenJson();
            const auto samples = (int64_t) 94815;

            expectEquals (BasicPitchFrontend::windowCount (samples), (int) golden["windows"]);
            expectEquals (BasicPitchFrontend::outputFrameCount (samples), (int) golden["frames"]);

            // One sample less than a whole hop must not add a window, and one
            // sample more must - the off-by-one that silently drops the end of a
            // take.
            const auto hop = (int64_t) BasicPitchFrontend::kHopSamples;
            const auto pad = (int64_t) BasicPitchFrontend::kLeadingPadSamples;
            expectEquals (BasicPitchFrontend::windowCount (hop - pad), 1);
            expectEquals (BasicPitchFrontend::windowCount (hop - pad + 1), 2);
            expectEquals (BasicPitchFrontend::windowCount (2 * hop - pad), 2);
            expectEquals (BasicPitchFrontend::windowCount (2 * hop - pad + 1), 3);

            // A window past the end of the signal is silence, not garbage.
            std::vector<float> padded (10, 0.5f);
            std::vector<float> window;
            BasicPitchFrontend::fillWindow (padded, 4, window);
            expectEquals ((int) window.size(), BasicPitchFrontend::kSamplesPerWindow);
            expectEquals (window[0], 0.5f);
            expectEquals (window[5], 0.5f);
            expectEquals (window[6], 0.0f);
            expectEquals (window[BasicPitchFrontend::kSamplesPerWindow - 1], 0.0f);
        }

        beginTest ("the model is in the binary and a session builds over it");
        {
            ModelLocator::Model model;
            juce::String error;

            expect (ModelLocator::find ("nmp_onnx", "nmp.onnx", model, error), error);
            expect (model.isValid());
            // 230444 bytes is the upstream file, and it is embedded rather than
            // copied out of one: the source says "built in" or the model came
            // from somewhere this build did not intend.
            expectEquals ((int) model.size, 230444);
            expectEquals (model.source, juce::String ("built in"));
            expect (model.owned.getSize() == 0, "an embedded model must not be copied");

            OrtSession session (model.data, model.size, "Basic Pitch", error);
            expect (session.isValid(), error);
            logMessage ("    ONNX Runtime " + OrtSession::runtimeVersion()
                          + ", execution provider " + session.executionProvider());

            // One real inference over one window of silence: shapes only, but
            // shapes are what a re-exported model would change.
            std::vector<float> window ((size_t) BasicPitchFrontend::kSamplesPerWindow, 0.0f);
            OrtSession::TensorView view;
            view.data = window.data();
            view.shape = { 1, (int64_t) BasicPitchFrontend::kSamplesPerWindow, 1 };

            std::vector<OrtSession::Tensor> outputs;
            const std::vector<const char*> outputNames { BasicPitchFrontend::kNoteOutput,
                                                         BasicPitchFrontend::kOnsetOutput,
                                                         BasicPitchFrontend::kContourOutput };

            expect (session.run ({ BasicPitchFrontend::kInputName }, { view },
                                 outputNames, outputs, error), error);
            expectEquals ((int) outputs.size(), 3);
            expectEquals ((int) outputs[0].dim (1), BasicPitchFrontend::kFramesPerWindow);
            expectEquals ((int) outputs[0].dim (2), BasicPitchFrontend::kNoteBins);
            expectEquals ((int) outputs[1].dim (2), BasicPitchFrontend::kNoteBins);
            expectEquals ((int) outputs[2].dim (2), BasicPitchFrontend::kContourBins);

            for (const auto value : outputs[0].data)
                if (value < 0.0f || value > 1.0f)
                {
                    expect (false, "a posteriorgram value is outside [0, 1]");
                    break;
                }
        }

        beginTest ("the post-processor recovers upstream's notes from upstream's posteriorgrams");
        {
            Golden golden;
            expect (loadGoldenBin (golden), "could not read BasicPitchGolden.bin");
            expectEquals (golden.bins, BasicPitchFrontend::kNoteBins);

            const auto expected = loadGoldenJson();
            expectEquals (golden.frames, (int) expected["frames"]);

            const auto events = BasicPitchNotes::convert (golden.notes, golden.onsets, {});
            expectMatchesGolden (events, expected["defaultBounds"], "default bounds");

            for (const auto& event : events)
            {
                expect (event.endFrame > event.startFrame, "a note ends before it starts");
                expect (event.pitch >= 21 && event.pitch <= 108, "a pitch is off the piano");
                expect (event.endTime > event.startTime);
                expect (std::abs (event.startTime
                                    - BasicPitchFrontend::frameToSeconds (event.startFrame)) < 1.0e-9);
            }
        }

        beginTest ("the bass hint clamps the output, and nothing else does");
        {
            Golden golden;
            expect (loadGoldenBin (golden), "could not read BasicPitchGolden.bin");
            const auto expected = loadGoldenJson();

            // The measured bound. 150 Hz, from the audition on this Mac; the
            // fixture carries a C4 exactly so that a bound that silently stopped
            // working would show up as a note that should not be there.
            const auto bass = BasicPitchNotes::boundsFor ({ "electric_bass" });
            expect (bass.maxFrequencyHz > 149.0f && bass.maxFrequencyHz < 151.0f,
                    "the bass bound is not 150 Hz any more - was the audition re-run?");

            const auto clamped = BasicPitchNotes::convert (golden.notes, golden.onsets, bass);
            expectMatchesGolden (clamped, expected["bassBounds150Hz"], "bass bounds");

            const auto unclamped = BasicPitchNotes::convert (golden.notes, golden.onsets, {});
            expect (clamped.size() < unclamped.size(),
                    "the bass bound removed nothing at all");

            for (const auto& event : clamped)
                expect (event.pitch <= 50, "the bass bound let a note through above D3");

            // Every hint that is not a bass leaves the model's own range alone.
            // A ceiling guessed for an unknown instrument would delete real
            // notes, which is the whole failure this table exists to avoid.
            for (const auto& generic : { "", "staff", "acoustic_guitar", "voice", "drums" })
            {
                const auto params = BasicPitchNotes::boundsFor ({ generic });
                expect (params.maxFrequencyHz < 0.0f,
                        juce::String ("\"") + generic + "\" was given a frequency ceiling");
                expect (params.minFrequencyHz < 0.0f);
            }

            expect (BasicPitchNotes::boundsFor ({}).maxFrequencyHz < 0.0f,
                    "an empty hint was given a frequency ceiling");

            // The names are matched case-insensitively and with surrounding
            // space trimmed, because a hint arrives over a JSON bridge.
            expect (BasicPitchNotes::boundsFor ({ "  Electric_Bass " }).maxFrequencyHz > 0.0f);

            for (const auto& name : BasicPitchNotes::bassInstrumentNames())
                expect (BasicPitchNotes::boundsFor ({ name }).maxFrequencyHz > 0.0f,
                        "a declared bass name was not recognised: " + name);
        }

        beginTest ("end to end: the wav goes in, upstream's posteriorgrams come out");
        {
            const auto wav = testDir().getChildFile ("BasicPitchFixture.wav");

            std::vector<float> mono;
            juce::String error;
            expect (BasicPitchFrontend::readMonoAt22050 (wav, mono, error), error);
            expectEquals ((int) mono.size(), 94815);

            ModelLocator::Model model;
            expect (ModelLocator::find ("nmp_onnx", "nmp.onnx", model, error), error);

            OrtSession session (model.data, model.size, "Basic Pitch", error);
            expect (session.isValid(), error);

            int lastCompleted = 0, lastTotal = 0;
            BasicPitchFrontend::Result result;
            const auto startedAt = juce::Time::getMillisecondCounterHiRes();

            expect (BasicPitchFrontend::analyse (session, mono,
                                                 [&] (int done, int total)
                                                 {
                                                     lastCompleted = done;
                                                     lastTotal = total;
                                                 },
                                                 nullptr, result, error), error);

            const auto elapsed = juce::Time::getMillisecondCounterHiRes() - startedAt;
            logMessage ("    4.30 s of audio in " + juce::String (elapsed, 1) + " ms wall clock ("
                          + juce::String (result.inferenceMs, 1) + " ms of it inference, "
                          + juce::String (result.windowsRun) + " windows) - "
                          + juce::String (4300.0 / juce::jmax (1.0, elapsed), 1) + "x real time");

            Golden golden;
            expect (loadGoldenBin (golden), "could not read BasicPitchGolden.bin");

            expectEquals ((int) result.notes.size(), golden.frames);
            expectEquals ((int) result.onsets.size(), golden.frames);
            expectEquals (lastCompleted, lastTotal);
            expectEquals (result.windowsRun, lastTotal);

            // THE REAL CHECK. If the framing, the leading pad, the window hop or
            // the unwrap trim were wrong, this is where it shows: the values
            // would still be in [0,1] and still look like a posteriorgram, and
            // they would be in the wrong places. 2e-3 is float noise between two
            // ORT builds on the same graph, not a fudge factor - the observed
            // maximum is reported below so a drift is visible rather than
            // absorbed.
            double worst = 0.0;

            for (size_t f = 0; f < result.notes.size(); ++f)
                for (size_t b = 0; b < result.notes[f].size(); ++b)
                {
                    worst = juce::jmax (worst, (double) std::abs (result.notes[f][b] - golden.notes[f][b]));
                    worst = juce::jmax (worst, (double) std::abs (result.onsets[f][b] - golden.onsets[f][b]));
                }

            logMessage ("    largest posteriorgram difference from the reference run: "
                          + juce::String (worst, 8));
            expect (worst < 2.0e-3,
                    "this build's posteriorgrams differ from the reference by " + juce::String (worst, 8));

            // And the notes that come out of them are real notes.
            const auto events = BasicPitchNotes::convert (result.notes, result.onsets, {});
            expect (! events.empty(), "no notes at all came out of the fixture");

            for (const auto& event : events)
            {
                expect (event.endTime > event.startTime);
                expect (event.pitch >= 21 && event.pitch <= 108);
                expect (event.amplitude >= 0.0 && event.amplitude <= 1.0);
            }

            expectMatchesGolden (events, loadGoldenJson()["defaultBounds"], "end to end");
        }

        beginTest ("a cancel lands inside the window loop, not at the end of the take");
        {
            const auto wav = testDir().getChildFile ("BasicPitchFixture.wav");

            std::vector<float> mono;
            juce::String error;
            expect (BasicPitchFrontend::readMonoAt22050 (wav, mono, error), error);

            ModelLocator::Model model;
            expect (ModelLocator::find ("nmp_onnx", "nmp.onnx", model, error), error);

            OrtSession session (model.data, model.size, "Basic Pitch", error);
            expect (session.isValid(), error);

            BasicPitchFrontend::Result result;
            int windowsSeen = 0;

            expect (! BasicPitchFrontend::analyse (session, mono,
                                                   [&] (int, int) { ++windowsSeen; },
                                                   [&] { return windowsSeen >= 1; },
                                                   result, error));
            expectEquals (error, juce::String ("cancelled"));
            expectEquals (windowsSeen, 1);
        }

        beginTest ("an empty or missing input is refused, not guessed at");
        {
            std::vector<float> mono;
            juce::String error;

            expect (! BasicPitchFrontend::readMonoAt22050 (testDir().getChildFile ("no-such-file.wav"),
                                                           mono, error));
            expect (error.isNotEmpty());

            ModelLocator::Model model;
            expect (! ModelLocator::find ("no_such_model", "no-such-model.onnx", model, error));
            expect (error.contains ("Looked in"), "the failure does not say where it looked");

            OrtSession empty (nullptr, 0, "nothing", error);
            expect (! empty.isValid());
            expect (error.isNotEmpty());
        }

        beginTest ("a silent signal produces no notes rather than a division by zero");
        {
            BasicPitchFrontend::Posteriorgram silent ((size_t) 200,
                                                      std::vector<float> ((size_t) BasicPitchFrontend::kNoteBins, 0.0f));
            const auto events = BasicPitchNotes::convert (silent, silent, {});
            expect (events.empty());
        }
    }
};

static BasicPitchTests basicPitchTests;
